default_platform(:android)

platform :android do
  desc "Deploy to Play Store"
  lane :deploy do
    upload_to_play_store(
      track: 'internal',
      aab: './mobile/build/app/outputs/bundle/release/app-release.aab',
      json_key: '../play-store-credentials.json'
    )
  end
end
