name: Publish release

on:
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Calculate version
        id: version
        run: |
          latest=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0")
          ver=${latest#v}
          IFS='.' read -r major minor patch <<< "$ver"
          newPatch=$((patch + 1))
          newVersion="$major.$minor.$newPatch"
          echo "Calculated new version: $newVersion"
          echo "version=$newVersion" >> $GITHUB_OUTPUT

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Setup Gradle Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.x"
          channel: "stable"

      - name: Create keystore
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > mobile/android/app/key.jks

      - name: Create key.properties
        run: |
          cat << EOF > key.properties
          storePassword=${{ secrets.KEYSTORE_PASSWORD }}
          keyPassword=${{ secrets.KEY_PASSWORD }}
          keyAlias=${{ secrets.KEY_ALIAS }}
          storeFile=key.jks
          EOF
          mv key.properties mobile/android/

      - name: Build mobile release APK
        run: |
          cd mobile
          flutter pub get
          flutter build apk --release
          mv build/app/outputs/flutter-apk/app-release.apk ../mobile.apk

      - name: Build example release APK
        run: |
          chmod +x ./gradlew
          ./gradlew :example:assembleRelease
          mv example/app/build/outputs/apk/release/app-release.apk example.apk

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            mobile.apk
            example.apk
          body_path: changelog.md
          draft: false
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}
          name: Release ${{ steps.version.outputs.version }}
          tag_name: v${{ steps.version.outputs.version }}
