name: Test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.4.2"
          bundler-cache: true
      - name: Setup Play Store credentials
        run: |
          echo "${{ secrets.PLAY_STORE_JSON_KEY }}" > play-store-credentials.json
      - name: Build and Deploy
        run: |
          bundle exec fastlane deploy
